server:
  port: 9898
  host: ip地址
spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://${server.host}:5432/my_blog?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
  mail:
    password: 
    username: @163.com
    default-encoding: UTF-8
    host: smtp.163.com
  redis:
    host: ${server.host}
    port: 6379
    password: password
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
mybatis:
  mapper-locations: classpath:/mappers/**
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
pagehelper:
  helper-dialect: postgresql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
  auto-dialect: true
meilisearch:
  apiHost: http://141.164.45.104:7700
  apiKey: zhengshuyuzuishuaile8889966
init:
  search: false
  random: false
gpt:
  model: text-davinci-002-render-sha-mobile
  token: token
upload:
#  5MB
  maxImageSize: 5242880
#  300MB
  maxFileSize: 314572800
  prefix: static/
  uri: https://www.shuyuz.com/static/
  path: J:/blog/static
logging:
  config: classpath:logback-async.xml
